// <auto-generated />
using System;
using Budgie.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Budgie.API.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20240904125400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Budgie.API.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("TransactionTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "games-and-software",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(5904),
                            Name = "Apps, Games & Software",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(5905)
                        },
                        new
                        {
                            Id = "car-insurance-and-maintenance",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(6715),
                            Name = "Car Insurance, Rego & Maintenance",
                            ParentId = "transport",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(6715)
                        },
                        new
                        {
                            Id = "family",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(7284),
                            Name = "Children & Family",
                            ParentId = "personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(7285)
                        },
                        new
                        {
                            Id = "good-life",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(7833),
                            Name = "Good Life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(7833)
                        },
                        new
                        {
                            Id = "groceries",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(8256),
                            Name = "Groceries",
                            ParentId = "home",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(8256)
                        },
                        new
                        {
                            Id = "booze",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(8760),
                            Name = "Booze",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(8760)
                        },
                        new
                        {
                            Id = "clothing-and-accessories",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(9184),
                            Name = "Clothing & Accessories",
                            ParentId = "personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(9184)
                        },
                        new
                        {
                            Id = "cycling",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(9671),
                            Name = "Cycling",
                            ParentId = "transport",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(9671)
                        },
                        new
                        {
                            Id = "homeware-and-appliances",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(146),
                            Name = "Homeware & Appliances",
                            ParentId = "home",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(147)
                        },
                        new
                        {
                            Id = "personal",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(579),
                            Name = "Personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(579)
                        },
                        new
                        {
                            Id = "education-and-student-loans",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(1062),
                            Name = "Education & Student Loans",
                            ParentId = "personal",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(1062)
                        },
                        new
                        {
                            Id = "events-and-gigs",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(1461),
                            Name = "Events & Gigs",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(1461)
                        },
                        new
                        {
                            Id = "fuel",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(1983),
                            Name = "Fuel",
                            ParentId = "transport",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(1983)
                        },
                        new
                        {
                            Id = "home",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(2438),
                            Name = "Home",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(2438)
                        },
                        new
                        {
                            Id = "internet",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(2849),
                            Name = "Internet",
                            ParentId = "home",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(2849)
                        },
                        new
                        {
                            Id = "fitness-and-wellbeing",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(3325),
                            Name = "Fitness & Wellbeing",
                            ParentId = "personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(3325)
                        },
                        new
                        {
                            Id = "hobbies",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(3789),
                            Name = "Hobbies",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = "home-maintenance-and-improvements",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(4196),
                            Name = "Maintenance & Improvements",
                            ParentId = "home",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(4196)
                        },
                        new
                        {
                            Id = "parking",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(4700),
                            Name = "Parking",
                            ParentId = "transport",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(4701)
                        },
                        new
                        {
                            Id = "transport",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(5129),
                            Name = "Transport",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(5130)
                        },
                        new
                        {
                            Id = "gifts-and-charity",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(5608),
                            Name = "Gifts & Charity",
                            ParentId = "personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(5609)
                        },
                        new
                        {
                            Id = "holidays-and-travel",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(6061),
                            Name = "Holidays & Travel",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(6062)
                        },
                        new
                        {
                            Id = "pets",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(6484),
                            Name = "Pets",
                            ParentId = "home",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(6484)
                        },
                        new
                        {
                            Id = "public-transport",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(6960),
                            Name = "Public Transport",
                            ParentId = "transport",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(6960)
                        },
                        new
                        {
                            Id = "hair-and-beauty",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(7420),
                            Name = "Hair & Beauty",
                            ParentId = "personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(7421)
                        },
                        new
                        {
                            Id = "lottery-and-gambling",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(7863),
                            Name = "Lottery & Gambling",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(7863)
                        },
                        new
                        {
                            Id = "home-insurance-and-rates",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(8306),
                            Name = "Rates & Insurance",
                            ParentId = "home",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(8307)
                        },
                        new
                        {
                            Id = "car-repayments",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(8776),
                            Name = "Repayments",
                            ParentId = "transport",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(8777)
                        },
                        new
                        {
                            Id = "health-and-medical",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(9219),
                            Name = "Health & Medical",
                            ParentId = "personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(9219)
                        },
                        new
                        {
                            Id = "pubs-and-bars",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(9733),
                            Name = "Pubs & Bars",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 167, DateTimeKind.Utc).AddTicks(9733)
                        },
                        new
                        {
                            Id = "rent-and-mortgage",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(143),
                            Name = "Rent & Mortgage",
                            ParentId = "home",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(144)
                        },
                        new
                        {
                            Id = "taxis-and-share-cars",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(638),
                            Name = "Taxis & Share Cars",
                            ParentId = "transport",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(639)
                        },
                        new
                        {
                            Id = "investments",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(1064),
                            Name = "Investments",
                            ParentId = "personal",
                            TransactionTypeId = "direct_credit",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(1064)
                        },
                        new
                        {
                            Id = "restaurants-and-cafes",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(1517),
                            Name = "Restaurants & Cafes",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(1517)
                        },
                        new
                        {
                            Id = "toll-roads",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(2001),
                            Name = "Tolls",
                            ParentId = "transport",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(2002)
                        },
                        new
                        {
                            Id = "utilities",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(2423),
                            Name = "Utilities",
                            ParentId = "home",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(2424)
                        },
                        new
                        {
                            Id = "life-admin",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(2858),
                            Name = "Life Admin",
                            ParentId = "personal",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(2858)
                        },
                        new
                        {
                            Id = "takeaway",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(3322),
                            Name = "Takeaway",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(3322)
                        },
                        new
                        {
                            Id = "mobile-phone",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(3784),
                            Name = "Mobile Phone",
                            ParentId = "personal",
                            TransactionTypeId = "payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(3784)
                        },
                        new
                        {
                            Id = "tobacco-and-vaping",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(4247),
                            Name = "Tobacco & Vaping",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(4247)
                        },
                        new
                        {
                            Id = "news-magazines-and-books",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(4791),
                            Name = "News, Magazines & Books",
                            ParentId = "personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(4791)
                        },
                        new
                        {
                            Id = "tv-and-music",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(5241),
                            Name = "TV, Music & Streaming",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(5241)
                        },
                        new
                        {
                            Id = "adult",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(5694),
                            Name = "Adult",
                            ParentId = "good-life",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(5695)
                        },
                        new
                        {
                            Id = "technology",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(6143),
                            Name = "Technology",
                            ParentId = "personal",
                            TransactionTypeId = "purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(6144)
                        },
                        new
                        {
                            Id = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(6597),
                            Name = "Transfer",
                            TransactionTypeId = "transfer",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(6597)
                        });
                });

            modelBuilder.Entity("Budgie.API.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedDescription")
                        .HasColumnType("text");

                    b.Property<string>("OriginalDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = -45.60m,
                            CategoryId = "restaurants-and-cafes",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 606, DateTimeKind.Utc).AddTicks(9667),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 1),
                            ModifiedDescription = "Uber Eats Delivery",
                            OriginalDescription = "UBER *EATS HELP.UBER.COM ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 606, DateTimeKind.Utc).AddTicks(9668),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Amount = -150.00m,
                            CategoryId = "groceries",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(735),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 2),
                            ModifiedDescription = "Woolworths Groceries",
                            OriginalDescription = "WOOLWORTHS 1234 SYDNEY ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(735),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 200.00m,
                            CategoryId = "clothing-and-accessories",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(1582),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 3),
                            OriginalDescription = "MYER DEPARTMENT STORE SYDNEY ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(1582),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Amount = -450.00m,
                            CategoryId = "holidays-and-travel",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(4181),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 4),
                            ModifiedDescription = "Flights to Melbourne",
                            OriginalDescription = "FLIGHT CENTRE MELBOURNE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(4182),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 15.99m,
                            CategoryId = "tv-and-music",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(5059),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 5),
                            OriginalDescription = "NETFLIX.COM 800-123-4567 ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(5059),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Amount = 500.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(7610),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 7),
                            OriginalDescription = "TRANSFER TO SAVINGS ACCOUNT ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(7610),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Amount = 200.00m,
                            CategoryId = "gifts-and-charity",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(8778),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 8),
                            ModifiedDescription = "Gift from Parents",
                            OriginalDescription = "TRANSFER FROM PARENTS ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(8778),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Amount = 75.50m,
                            CategoryId = "home-maintenance-and-improvements",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(9405),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 9),
                            OriginalDescription = "BUNNINGS WAREHOUSE BRISBANE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(9405),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Amount = 120.00m,
                            CategoryId = "technology",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(9904),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 10),
                            OriginalDescription = "AMAZON AU MELBOURNE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 607, DateTimeKind.Utc).AddTicks(9904),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Amount = 60.00m,
                            CategoryId = "fuel",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(2582),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 1),
                            OriginalDescription = "SHELL SERVICE STATION PERTH ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(2583),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 12L,
                            Amount = 70.00m,
                            CategoryId = "fuel",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(3297),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 2),
                            OriginalDescription = "BP AUSTRALIA PERTH ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(3298),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            Amount = 250.00m,
                            CategoryId = "groceries",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(5135),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 4),
                            OriginalDescription = "WOOLWORTHS 5678 PERTH ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(5136),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 15L,
                            Amount = 15.00m,
                            CategoryId = "parking",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(5960),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 5),
                            OriginalDescription = "CITY OF PERTH PARKING ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(5961),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            Amount = 800.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(7177),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 7),
                            OriginalDescription = "TRANSFER TO SAVINGS ACCOUNT ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(7177),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            Amount = 500.00m,
                            CategoryId = "gifts-and-charity",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(7688),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 8),
                            ModifiedDescription = "Loan from Sister",
                            OriginalDescription = "TRANSFER FROM SISTER ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(7688),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            Amount = 120.00m,
                            CategoryId = "fitness-and-wellbeing",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(8096),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 9),
                            OriginalDescription = "REBEL SPORT BRISBANE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(8096),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            Amount = 45.00m,
                            CategoryId = "mobile-phone",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(8607),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 10),
                            OriginalDescription = "OPTUS BILL PAYMENT ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(8608),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            Amount = -23.45m,
                            CategoryId = "transport",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(9695),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 1),
                            ModifiedDescription = "Uber Rides",
                            OriginalDescription = "UBER *RIDES SYDNEY ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 608, DateTimeKind.Utc).AddTicks(9695),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 22L,
                            Amount = -180.00m,
                            CategoryId = "groceries",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(2816),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 2),
                            ModifiedDescription = "Groceries",
                            OriginalDescription = "COLES SUPERMARKET ADELAIDE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(2817),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 23L,
                            Amount = 500.00m,
                            CategoryId = "technology",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(3430),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 3),
                            OriginalDescription = "JB HI-FI MELBOURNE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(3430),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 24L,
                            Amount = 320.00m,
                            CategoryId = "homeware-and-appliances",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(3968),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 4),
                            OriginalDescription = "HARVEY NORMAN PERTH ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(3968),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 25L,
                            Amount = 15.99m,
                            CategoryId = "tv-and-music",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(4505),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 5),
                            OriginalDescription = "NETFLIX.COM 800-123-4567 ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(4505),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 27L,
                            Amount = 1000.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(5456),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 7),
                            OriginalDescription = "TRANSFER TO MORTGAGE ACCOUNT ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(5456),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 28L,
                            Amount = 100.00m,
                            CategoryId = "gifts-and-charity",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(5884),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 8),
                            ModifiedDescription = "Gift from Friend",
                            OriginalDescription = "TRANSFER FROM FRIEND ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(5884),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 29L,
                            Amount = 40.00m,
                            CategoryId = "clothing-and-accessories",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(6367),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 9),
                            OriginalDescription = "BIG W SYDNEY ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(6368),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 30L,
                            Amount = 60.00m,
                            CategoryId = "booze",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(8149),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 10),
                            OriginalDescription = "DAN MURPHY'S BRISBANE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(8150),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 31L,
                            Amount = 60.00m,
                            CategoryId = "groceries",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(8736),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 11),
                            OriginalDescription = "WOOLWORTHS 9999 BRISBANE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(8736),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 32L,
                            Amount = 25.00m,
                            CategoryId = "parking",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(9148),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 12),
                            OriginalDescription = "CITY OF SYDNEY PARKING ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(9148),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 33L,
                            Amount = 150.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(9728),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 13),
                            OriginalDescription = "TRANSFER TO CREDIT CARD ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 609, DateTimeKind.Utc).AddTicks(9728),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 34L,
                            Amount = 70.00m,
                            CategoryId = "utilities",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(1558),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 14),
                            OriginalDescription = "TELSTRA BILL PAYMENT ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(1559),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 35L,
                            Amount = 200.00m,
                            CategoryId = "clothing-and-accessories",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(2365),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 11),
                            OriginalDescription = "WESTFIELD SHOPPING CENTRE PERTH ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(2365),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 37L,
                            Amount = 250.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(3284),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 13),
                            OriginalDescription = "TRANSFER TO CREDIT CARD ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(3285),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 38L,
                            Amount = 15.00m,
                            CategoryId = "restaurants-and-cafes",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(3800),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 14),
                            OriginalDescription = "SUBWAY FRANCHISE ADELAIDE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(3801),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 39L,
                            Amount = 1200.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(4284),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 11),
                            OriginalDescription = "BOQ HOME LOAN PAYMENT ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(4284),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 41L,
                            Amount = 200.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(5191),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 13),
                            OriginalDescription = "TRANSFER TO SAVINGS ACCOUNT ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(5191),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 43L,
                            Amount = 900.00m,
                            CategoryId = "rent-and-mortgage",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(6272),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 15),
                            OriginalDescription = "AUSSIE HOME LOANS SYDNEY ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(6273),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 44L,
                            Amount = 8.00m,
                            CategoryId = "restaurants-and-cafes",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(6712),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 16),
                            OriginalDescription = "BOOST JUICE BRISBANE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(6713),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 46L,
                            Amount = 60.00m,
                            CategoryId = "home-maintenance-and-improvements",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(7732),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 16),
                            OriginalDescription = "BUNNINGS WAREHOUSE PERTH ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(7733),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 47L,
                            Amount = -120.00m,
                            CategoryId = "groceries",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(8426),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 15),
                            ModifiedDescription = "Groceries",
                            OriginalDescription = "COLES SUPERMARKET MELBOURNE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(8427),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 48L,
                            Amount = 250.00m,
                            CategoryId = "technology",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(9401),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 16),
                            OriginalDescription = "KOGAN.COM SYDNEY ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 610, DateTimeKind.Utc).AddTicks(9401),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 49L,
                            Amount = 150.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(107),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 17),
                            OriginalDescription = "TRANSFER TO FRIEND ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(107),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 50L,
                            Amount = -60.00m,
                            CategoryId = "restaurants-and-cafes",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(1071),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 18),
                            ModifiedDescription = "Tickets",
                            OriginalDescription = "MELBOURNE ZOO MELBOURNE ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(1071),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 51L,
                            Amount = 200.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(1621),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 17),
                            OriginalDescription = "TRANSFER TO FAMILY ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(1622),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 52L,
                            Amount = 500.00m,
                            CategoryId = "transfer",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(2145),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 18),
                            OriginalDescription = "TRANSFER TO SUPERANNUATION ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(2145),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 54L,
                            Amount = 100.00m,
                            CategoryId = "health-and-medical",
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(3025),
                            Currency = "AUD",
                            Date = new DateOnly(2023, 8, 18),
                            OriginalDescription = "MEDIBANK PRIVATE SYDNEY ;",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 611, DateTimeKind.Utc).AddTicks(3026),
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("Budgie.API.Models.TransactionType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("CanHaveCategory")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = "purchase",
                            CanHaveCategory = false,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(2426),
                            Name = "Purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(2426)
                        },
                        new
                        {
                            Id = "international_purchase",
                            CanHaveCategory = false,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(2924),
                            Name = "International Purchase",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(2924)
                        },
                        new
                        {
                            Id = "direct_credit",
                            CanHaveCategory = false,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(3419),
                            Name = "Direct Credit",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(3420)
                        },
                        new
                        {
                            Id = "refund",
                            CanHaveCategory = false,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(3858),
                            Name = "Refund",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(3859)
                        },
                        new
                        {
                            Id = "payment",
                            CanHaveCategory = false,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(4288),
                            Name = "Payment",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(4288)
                        },
                        new
                        {
                            Id = "transfer",
                            CanHaveCategory = false,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(4668),
                            Name = "Transfer",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 166, DateTimeKind.Utc).AddTicks(4669)
                        });
                });

            modelBuilder.Entity("Budgie.API.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(7718),
                            Email = "user@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$T1z0uc3wTz4heE7E2sMuFesoXyWnp4E5xJk0Sl.DdMYrvMlUk9jbO",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 168, DateTimeKind.Utc).AddTicks(7719)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 308, DateTimeKind.Utc).AddTicks(1768),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$uWQuejCzKXuMzFkumEXRHuxGNXkbr4AlzbeRYmG.ZPpKlsikin90u",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 308, DateTimeKind.Utc).AddTicks(1768)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 446, DateTimeKind.Utc).AddTicks(4205),
                            Email = "user3@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$BObAZD/j21p8iGN2edkYGu274D2BrjRsM4rDrMghCeHyqgaKnIjWG",
                            UpdatedAt = new DateTime(2024, 9, 4, 12, 53, 59, 446, DateTimeKind.Utc).AddTicks(4206)
                        });
                });

            modelBuilder.Entity("Budgie.API.Models.Category", b =>
                {
                    b.HasOne("Budgie.API.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Budgie.API.Models.TransactionType", "TransactionType")
                        .WithMany("Categories")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Budgie.API.Models.Transaction", b =>
                {
                    b.HasOne("Budgie.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Budgie.API.Models.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Budgie.API.Models.TransactionType", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
