// <auto-generated />
using System;
using BudgetApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetApi.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20240825032257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetApi.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = "9f380f71-db1c-4d9d-9f4c-91244511a8d3",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = "cbdf0d2b-198f-48d2-9e90-4ea086b4610c",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = "bc109365-15a8-49ad-a017-7623c0370755",
                            Name = "Dining"
                        },
                        new
                        {
                            Id = "60bda4c4-4d17-4a29-9fe9-0ede28cf3b2b",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = "4e2fe63c-da15-4a26-8499-105a48b0c8bc",
                            Name = "Rent"
                        },
                        new
                        {
                            Id = "a9e4ee9e-1297-409a-a730-a62a38584b1d",
                            Name = "Home Improvement"
                        },
                        new
                        {
                            Id = "ceb6ee8e-f240-456b-b754-d58846ae7063",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = "08fccd17-af1b-42a5-9bc9-8a6dd1cf1bf8",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = "aa32b77d-87da-4c63-856b-6897094702e8",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = "dd067c60-4b41-44dd-8e61-9565b9edc975",
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = "a8fed1bd-4d3a-4df6-b6b4-1742069573f6",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = "e0a001e6-b0c9-4b28-b5c4-764a0f79d120",
                            Name = "Transfer"
                        },
                        new
                        {
                            Id = "13272b56-8e40-4f15-b355-76143b272190",
                            Name = "Income"
                        });
                });

            modelBuilder.Entity("BudgetApi.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 85.50m,
                            CategoryId = "9f380f71-db1c-4d9d-9f4c-91244511a8d3",
                            Date = new DateOnly(2024, 1, 1),
                            Description = "Coles Supermarket Southbank",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 120.75m,
                            CategoryId = "cbdf0d2b-198f-48d2-9e90-4ea086b4610c",
                            Date = new DateOnly(2024, 1, 2),
                            Description = "Electricity Bill - AGL",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 6.20m,
                            CategoryId = "bc109365-15a8-49ad-a017-7623c0370755",
                            Date = new DateOnly(2024, 1, 5),
                            Description = "Starbucks Queen St",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 50.00m,
                            CategoryId = "60bda4c4-4d17-4a29-9fe9-0ede28cf3b2b",
                            Date = new DateOnly(2024, 1, 7),
                            Description = "Myki Top-Up",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 1500.00m,
                            CategoryId = "4e2fe63c-da15-4a26-8499-105a48b0c8bc",
                            Date = new DateOnly(2024, 1, 10),
                            Description = "Rent - 123 Main St",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 6L,
                            Amount = 45.00m,
                            CategoryId = "a9e4ee9e-1297-409a-a730-a62a38584b1d",
                            Date = new DateOnly(2024, 1, 12),
                            Description = "Bunnings Hardware Capalaba",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 7L,
                            Amount = 19.99m,
                            CategoryId = "ceb6ee8e-f240-456b-b754-d58846ae7063",
                            Date = new DateOnly(2024, 1, 15),
                            Description = "Netflix Subscription",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 8L,
                            Amount = 60.00m,
                            CategoryId = "cbdf0d2b-198f-48d2-9e90-4ea086b4610c",
                            Date = new DateOnly(2024, 1, 18),
                            Description = "Optus Bill",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 9L,
                            Amount = 75.30m,
                            CategoryId = "60bda4c4-4d17-4a29-9fe9-0ede28cf3b2b",
                            Date = new DateOnly(2024, 1, 20),
                            Description = "BP Fuel Cannon Hill",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 10L,
                            Amount = 25.50m,
                            CategoryId = "08fccd17-af1b-42a5-9bc9-8a6dd1cf1bf8",
                            Date = new DateOnly(2024, 1, 22),
                            Description = "Kmart Purchase Carindale",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 11L,
                            Amount = 450.00m,
                            CategoryId = "aa32b77d-87da-4c63-856b-6897094702e8",
                            Date = new DateOnly(2024, 1, 25),
                            Description = "Qantas Flight QF123",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 12L,
                            Amount = 92.45m,
                            CategoryId = "9f380f71-db1c-4d9d-9f4c-91244511a8d3",
                            Date = new DateOnly(2024, 1, 27),
                            Description = "Woolworths Grocery Morningside",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 13L,
                            Amount = 40.00m,
                            CategoryId = "dd067c60-4b41-44dd-8e61-9565b9edc975",
                            Date = new DateOnly(2024, 1, 30),
                            Description = "Goodlife Gym Membership",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 14L,
                            Amount = 32.80m,
                            CategoryId = "bc109365-15a8-49ad-a017-7623c0370755",
                            Date = new DateOnly(2024, 2, 1),
                            Description = "Uber Eats Order",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 15L,
                            Amount = 11.99m,
                            CategoryId = "ceb6ee8e-f240-456b-b754-d58846ae7063",
                            Date = new DateOnly(2024, 2, 3),
                            Description = "Spotify Subscription",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 16L,
                            Amount = 30.00m,
                            CategoryId = "a8fed1bd-4d3a-4df6-b6b4-1742069573f6",
                            Date = new DateOnly(2024, 2, 5),
                            Description = "Medicare Bulk Billing",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 17L,
                            Amount = 150.00m,
                            CategoryId = "08fccd17-af1b-42a5-9bc9-8a6dd1cf1bf8",
                            Date = new DateOnly(2024, 2, 7),
                            Description = "JB Hi-Fi Electronics Purchase",
                            Type = 1,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 18L,
                            Amount = 3000.00m,
                            CategoryId = "13272b56-8e40-4f15-b355-76143b272190",
                            Date = new DateOnly(2024, 2, 8),
                            Description = "Salary Deposit",
                            Type = 0,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        },
                        new
                        {
                            Id = 19L,
                            Amount = 500.00m,
                            CategoryId = "e0a001e6-b0c9-4b28-b5c4-764a0f79d120",
                            Date = new DateOnly(2024, 2, 10),
                            Description = "Savings Transfer",
                            Type = 2,
                            UserId = "053aac4e-0ea9-4006-9c90-30ec34e93f52"
                        });
                });

            modelBuilder.Entity("BudgetApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "053aac4e-0ea9-4006-9c90-30ec34e93f52",
                            Email = "user@example.com",
                            PasswordHash = "$2a$11$5cx6Vsp6aROK8GL8M3buauSuHIQFhorIZr3C3HFmNOO1OQ/d2YaMa"
                        });
                });

            modelBuilder.Entity("BudgetApi.Models.Transaction", b =>
                {
                    b.HasOne("BudgetApi.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetApi.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
